### ISSUE TITLE
使用时出现“未在当前目录的路径中查找到：SteamLibrary\steamapps\workshop\content”问题

### ISSUE THREAD

**Issue by ZSXB2468** [LiuJiewenTT/vpet_modsync#1]
如题，附上命令行截图
![Clip_20240317_033855](https://github.com/LiuJiewenTT/vpet_modsync/assets/62994932/24526565-178f-4b5b-85e2-3931a51e4981)

**Comment by LiuJiewenTT** [comment]
抱歉，未考虑到存在`Steam\steamapps`目录下的情况，是我的疏忽。
临时解决方案1：在Steam库中将Vpet移出这个储存库即可。
临时解决方案2：用任意文本编辑器打开脚本，将`SteamLibrary`替换成`Steam`即可。

在我的这种情况下能正常运行（供参考）：
![image](https://github.com/LiuJiewenTT/vpet_modsync/assets/43092274/0a849b30-c75e-44ab-88ef-eea5e21d73b8)

等有空了会修复这个问题。

**Comment by ZSXB2468** [comment]
感谢

**Comment by LiuJiewenTT** [comment]
已在https://github.com/LiuJiewenTT/vpet_modsync/commit/ed6c39c25ed9cbb863aa77283fdc341340d80851 修复
